// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_prd.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_PnGSnJb3psZdsTnqEpqLEkGOzNsFL-k',
    appId: '1:242707161227:web:754325829ca34c485f348e',
    messagingSenderId: '242707161227',
    projectId: 'instride-health',
    authDomain: 'instride-health.firebaseapp.com',
    storageBucket: 'instride-health.appspot.com',
    measurementId: 'G-F1FKMELZLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqBylYfQIHm3oSWyLsC3Qj1MVRC4MPpbw',
    appId: '1:242707161227:android:c302164966903e2f5f348e',
    messagingSenderId: '242707161227',
    projectId: 'instride-health',
    storageBucket: 'instride-health.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAc2zCmFR-Ku1byvYINJH6cuh31QYXUog',
    appId: '1:242707161227:ios:fcaf06de912ce2255f348e',
    messagingSenderId: '242707161227',
    projectId: 'instride-health',
    storageBucket: 'instride-health.appspot.com',
    androidClientId: '242707161227-cbm3s77qpjien0j4l2sn4q5nt3lailll.apps.googleusercontent.com',
    iosClientId: '242707161227-5emjmqbv35dlt5b6k782gqsu91l4l5a0.apps.googleusercontent.com',
    iosBundleId: 'com.instride.health',
  );
}
