// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_uat.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDemmKrEzeu0X8ON2WGJ6PXWBzYCqDfutg',
    appId: '1:140105646362:web:1cae6ae099bf62bc46eca3',
    messagingSenderId: '140105646362',
    projectId: 'instride-health-uat',
    authDomain: 'instride-health-uat.firebaseapp.com',
    storageBucket: 'instride-health-uat.appspot.com',
    measurementId: 'G-X1JLLF5KGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj6j1hFbzjaGUM-Nhh16zgtoBvVC4Xbbw',
    appId: '1:140105646362:android:f6cdd75db35e337446eca3',
    messagingSenderId: '140105646362',
    projectId: 'instride-health-uat',
    storageBucket: 'instride-health-uat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Kfa58gfZVcLukzRKMiv3Nn7Qe1oA3eQ',
    appId: '1:140105646362:ios:e907fe4ed88acf9846eca3',
    messagingSenderId: '140105646362',
    projectId: 'instride-health-uat',
    storageBucket: 'instride-health-uat.appspot.com',
    androidClientId: '140105646362-84hp4p5kr3g7cf2b37v6fj1hssqgaudp.apps.googleusercontent.com',
    iosClientId: '140105646362-dkhu2rk1o0oofmnlci9kef2ol6bansu8.apps.googleusercontent.com',
    iosBundleId: 'com.instride.health.uat',
  );
}
