// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_sit.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFAj4ecwB0VtEXOUqHyLBvsioIfTO_NfA',
    appId: '1:62706022715:web:ca4fdc980f3d3658521f1e',
    messagingSenderId: '62706022715',
    projectId: 'instride-health-sit',
    authDomain: 'instride-health-sit.firebaseapp.com',
    storageBucket: 'instride-health-sit.appspot.com',
    measurementId: 'G-FZLNG0WWCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq_ZsCZfvuGXKGqXJ3k_-TBvVXM8yPg4w',
    appId: '1:62706022715:android:fffe2edbb2cab3c1521f1e',
    messagingSenderId: '62706022715',
    projectId: 'instride-health-sit',
    storageBucket: 'instride-health-sit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIRrLboaXAJdhIsFfskACPpq5-hidcrI4',
    appId: '1:62706022715:ios:f0281c292fe99fe5521f1e',
    messagingSenderId: '62706022715',
    projectId: 'instride-health-sit',
    storageBucket: 'instride-health-sit.appspot.com',
    iosClientId: '62706022715-qv64cjpemoecl5hh4rtk5vm58k9na74d.apps.googleusercontent.com',
    iosBundleId: 'com.instride.health.sit',
  );
}
